name: Deploy prod_cf to VPS

on:
  push:
    branches:
      - prod_cf

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: SSH into VPS and deploy
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.HOST }} << 'EOF'
            cd /var/www/zenime
            sudo git fetch origin prod_cf
            sudo git checkout prod_cf
            sudo git pull origin prod_cf
            sudo rm -rf dist
            sudo npm install
            sudo npm run build
          EOF
